# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20170714_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/home/humdah/PycharmProjects/InstaD4/the-lab/insta/instagram/avatars/default_avatar.png', upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
