# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_auto_20170716_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='user',
            name='width_field',
        ),
    ]
