# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_auto_20170716_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
