# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_auto_20170716_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.png', height_field='height_field', upload_to='avatars', width_field='width_field'),
        ),
    ]
