# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0015_auto_20170717_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_avatar.png', upload_to='posts/'),
        ),
    ]
