# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0019_auto_20170721_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow_Relation',
            new_name='FollowRelation',
        ),
    ]
