# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0021_auto_20170721_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='like_timestamp',
            new_name='timestamp',
        ),
    ]
