# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0022_auto_20170724_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.png', height_field='height_field', null=True, upload_to='avatars/', width_field='width_field'),
        ),
    ]
